version: '3'

networks:
  service_network:
    external: true

services:
  son-infra:
    build: ./vim-adaptor/
    image: son-infra:SNAPSHOT
    conntainer_name: son-infra
    networks:
      - service_network
    command: ./run_local.sh
