version: '3'

networks:
  service_network:
    external: true

services:
  son-infra:
    build: .
    image: son-infra:SNAPSHOT
    container_name: son-infra
    networks:
      - service_network
    command: /run_local.sh
